In [1]:
import pandas as pd
from sklearn.datasets import load_breast_cancer

In [2]:
data=load_breast_cancer()

In [4]:
X=data.data
y=data.target

In [5]:
print(X.shape)

(569, 30)

In [13]:
import pandas as pd

df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [8]:
print(data.target_names)

# malignant means cancerous 
# benign means non can

['malignant' 'benign']

In [19]:
from sklearn.model_selection import train_test_split
X=df.drop('target',axis=1)
y=df['target']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.4,random_state=42)

In [20]:
from sklearn.linear_model import LogisticRegression

In [23]:
lg=LogisticRegression()
lg.fit(X_train,y_train)

C:\Users\GYANDEEP\Desktop\numpy\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [24]:
y_pred=lg.predict(X_test)

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
accuracy_score(y_pred,y_test)

0.9649122807017544

In [28]:
from sklearn.tree import DecisionTreeClassifier

In [29]:
dt=DecisionTreeClassifier()

In [30]:
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [32]:
dy_pred=dt.predict(X_test)

In [33]:
accuracy_score(dy_pred,y_test)

0.9166666666666666

In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
rt=RandomForestClassifier()

In [36]:
rt.fit(X_train,y_train)

RandomForestClassifier()

In [37]:
ry_pred=rt.predict(X_test)

In [38]:
accuracy_score(ry_pred,y_test)

0.9692982456140351

In [41]:
importance_df = pd.DataFrame({
    'Feature': data.feature_names,
    'Importance': rt.feature_importances_
})

importance_df.sort_values(
    by='Importance',
    ascending=False
)

                    Feature  Importance
27     worst concave points    0.164451
7       mean concave points    0.122004
23               worst area    0.104986
22          worst perimeter    0.101305
20             worst radius    0.093284
6            mean concavity    0.067433
2            mean perimeter    0.040788
3                 mean area    0.037389
26          worst concavity    0.035144
13               area error    0.030180
21            worst texture    0.026047
0               mean radius    0.025532
10             radius error    0.020111
25        worst compactness    0.014626
28           worst symmetry    0.014098
24         worst smoothness    0.012950
1              mean texture    0.012922
5          mean compactness    0.012740
16          concavity error    0.008806
18           symmetry error    0.006515
17     concave points error    0.006447
14         smoothness error    0.006302
12          perimeter error    0.006112
9    mean fractal dimension    0.005997
29  worst fractal dimension    0.004600
4           mean smoothness    0.004550
19  fractal dimension error    0.004374
15        compactness error    0.004092
11            texture error    0.003508
8             mean symmetry    0.002707

### With Pipelines With LogisticRegression

In [42]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [43]:
pipe=Pipeline([
    ('scaler',StandardScaler()),
    ('model',LogisticRegression()),
])

In [44]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('model', LogisticRegression())])

In [45]:
py_pred=pipe.predict(X_test)

In [46]:
accuracy_score(py_pred,y_test)

0.9824561403508771

### Pipeline with RandomForest

In [72]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

In [73]:
pipe=Pipeline([
    ('scaler',StandardScaler()),
    ('model',RandomForestClassifier())
])

In [74]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', RandomForestClassifier())])

In [75]:
py_pred=pipe.predict(X_test)

In [76]:
accuracy_score(py_pred,y_test)

0.9707602339181286

### GridSearch CV

In [77]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

In [78]:
params={
    'n_estimators':[10,20,40,60],
    'max_depth':[3,5,8,None]
}

In [79]:
grid=GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid=params,
    cv=6
)

In [80]:
grid.fit(X_train,y_train)

GridSearchCV(cv=6, estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_depth': [3, 5, 8, None],
                         'n_estimators': [10, 20, 40, 60]})

In [81]:
accuracy_score(grid.predict(X_test),y_test)

0.9766081871345029

In [82]:
print('Best_parameters',grid.best_params_)
print("best_score",grid.best_score_)

Best_parameters {'max_depth': 5, 'n_estimators': 10}
best_score 0.9523217247097845

In [83]:
print(grid.cv_results_['mean_test_score'])

[0.94233379 0.94979647 0.94474597 0.93977084 0.95232172 0.94730891
 0.94470828 0.94467059 0.9372079  0.94723353 0.9496834  0.95220865
 0.93724559 0.94474597 0.94719584 0.94972109]

In [84]:
import pickle

pickle.dump(pipe, open('cancer_model.pkl', 'wb'))